export const SCENE_CONSTANTS = {
  NODE_SEGMENTS: 32,
  NODE_DEFAULT_RADIUS: 1,
  NODE_SELECTED_RADIUS: 1.2,
  EDGE_DEFAULT_WIDTH: 0.1,
  CAMERA_FOV: 50,
  CAMERA_NEAR: 0.1,
  CAMERA_FAR: 1000,
  CAMERA_POSITION: [0, 0, 50] as [number, number, number],
  MAX_NODES: 2000,
  MAX_EDGES: 5000,
} as const;